### PR TITLE
Adds blue SS14 logo

### PR DESCRIPTION
**Pull request by fiercestwarrior**
Made by Injazz

### CODE REVIEW

**Comment by PJB3005** [comment]
I mean are we ever going to use this? It looks pretty bad.

**Comment by fiercestwarrior** [comment]
¯\_(ツ)_/¯

also how does it look bad. it's pretty much the same except its blue.

**Comment by PJB3005** [comment]
Different shape of the 4.

**Comment by Injazz** [comment]
I suck at this please don't

**Pull request closed without merging**
