### PR TITLE
new logo for: sunrise, fishstation, lust-station, newera-station

### PR DESCRIPTION
**Pull request by cryals**
I've redone all the pictures. png 1024x1024 🫠

6cf3a45a40da0aa8c44da6f6872de6fc

### CODE REVIEW

**Comment by PJB3005** [comment]
This replaces #28?

**Comment by cryals** [comment]
> This replaces #28?

Yes, it replaces #28 
--
this is the version of an adequate person.

**Comment by cryals** [comment]
Yes, it replaces #28

**Review by PJB3005 — CHANGES_REQUESTED** [review]
All of these PNGs are re-exports from a jpeg, please upload the actual original JPEG so I don't clog this repo with compression artifacts.

**Comment by cryals** [comment]
> All of these PNGs are re-exports from a jpeg, please upload the actual original JPEG so I don't clog this repo with compression artifacts.

I didn't really understand what you were talking about... I cropped and resized this photo using lunacy (analog figma) and exported it immediately to PNG. And the sources themselves are also in png (except for newera-station, it is in jpg).

**Comment by cryals** [comment]
Are you talking about something like that?
image

**Comment by cryals** [comment]
so do that...

**Comment by cryals** [comment]
I no longer work for SUNRISE.

**Pull request closed without merging**
